# Generated by Django 3.0.2 on 2020-01-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='primaryCategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
