# Generated by Django 2.1.15 on 2020-03-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_contact',
            field=models.CharField(default='7874969627', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(default='pruthvibarot@gmail.com', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(default='pruthvi', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_mgmt.RoomType'),
        ),
    ]
