# Generated by Django 2.2 on 2019-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0015_visitor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
