# Generated by Django 2.2 on 2019-12-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0017_auto_20191230_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='image',
            field=models.FileField(upload_to='media'),
        ),
    ]
