# Generated by Django 3.0.2 on 2020-01-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0018_auto_20191230_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='image',
            field=models.FileField(upload_to='image/'),
        ),
    ]
