# Generated by Django 3.0.2 on 2020-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0019_auto_20200122_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
